[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls", "json", "gzip"] }
anti-vm = "0.1"