[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
pgp.workspace = true
rand.workspace = true
zeroize.workspace = true
argon2.workspace = true
chacha20poly1305.workspace = true
smallvec = "1"
